// Generated by CoffeeScript 1.3.3
(function() {
  var Weather;

  Weather = (function() {

    function Weather() {}

    Weather.prototype.init = function() {
      console.log("initializing");
      this.forcastApikey = "0fe656d926f844bc4c0745ac4ea9814f";
      this.yahooAppId = "pmQ_VnzV34FddFT6do_XVxcjzkrjmeKzNpJjLP1MqfPSEN6yCN0vunwBt8QbZYWEc65EPzD6o8VVmDYXTQZbPY0DkXSGUO4-";
      this.yahooURL = "http://where.yahooapis.com/v1/places.q('[place')?appid=[appid]";
      this.setupCache();
      this.checkForecast();
      this.setupMainView();
      this.setupSideMenu();
      return true;
    };

    Weather.prototype.setupCache = function() {
      console.log("setting up cache");
      if (localStorage.getItem("initialized" !== "false")) {
        localStorage.setItem("initialized", "false");
        localStorage.setItem("unit", "c");
        localStorage.setItem("city1", "Canterbury");
        localStorage.setItem("city2", "Cairo");
        localStorage.setItem("city3", "New York");
      }
      return true;
    };

    Weather.prototype.checkForecast = function() {
      console.log("checking forecast ");
      return true;
    };

    Weather.prototype.setupMainView = function() {
      console.log("setting up main View");
      return true;
    };

    Weather.prototype.setupSideMenu = function() {
      console.log("setting up sidemenu");
      return true;
    };

    return Weather;

  })();

  window.weather = new Weather;

  jQuery(function() {
    return window.weather.init();
  });

}).call(this);
